# Generated by Django 4.0.3 on 2022-04-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название проекта')),
                ('github_slug', models.CharField(max_length=128, verbose_name='Репозиторий')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('styding_year', models.PositiveSmallIntegerField(verbose_name='Учебный год')),
                ('is_main', models.BooleanField(default=False, verbose_name='Сделать основным')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('education_group', models.CharField(max_length=32, verbose_name='Группа студента')),
                ('education_type', models.CharField(max_length=32, verbose_name='Форма обучения')),
                ('github_username', models.CharField(max_length=32, verbose_name='Имя пользователя GitHub')),
                ('vk_uid', models.CharField(max_length=32, verbose_name='ID пользователя VK')),
                ('is_leader', models.BooleanField(verbose_name='Сделать лидером команды')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='year_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yeargroup'),
        ),
    ]
