# Generated by Django 4.0.3 on 2022-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(max_length=32, null=True, verbose_name='Отчество'),
        ),
    ]
