# Generated by Django 4.0.3 on 2022-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, max_length=32, verbose_name='Отчество'),
        ),
    ]
